apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkel-inntekt
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 5
  readiness:
    path: /isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvsparkelinntekt
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-sparkel-inntekt-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: INNTEKTSKOMPONENT_BASE_URL
      value: https://app-q1.adeo.no/inntektskomponenten-ws/rs
